/*
 * test_trace.c - Verify FridaTrace library on macOS.
 *
 * This test program:
 *   1. Starts instruction tracing on itself
 *   2. Executes some known functions
 *   3. Stops tracing
 *   4. Prints statistics
 *
 * Build:
 *   See the build command generated by the Makefile or build script.
 */

#include "gum.h"
#include "gumtrace.h"
#include "gumtracerecorder.h"
#include <stdio.h>
#include <string.h>
#include <unistd.h>

/* Some test functions to generate traceable calls */
static int fibonacci(int n)
{
    if (n <= 1) return n;
    return fibonacci(n - 1) + fibonacci(n - 2);
}

static void do_string_work(void)
{
    char buf[256];
    for (int i = 0; i < 10; i++)
    {
        snprintf(buf, sizeof(buf), "iteration %d", i);
        strlen(buf);
    }
}

static void do_math_work(void)
{
    volatile double result = 1.0;
    for (int i = 1; i <= 100; i++)
    {
        result *= 1.01;
    }
}

int main(int argc, char *argv[])
{
    const char *output_path = "/tmp/fridatrace_test.bin";
    GumTraceSession *session;

    printf("=== FridaTrace Test ===\n\n");

    /* Start tracing - trace all modules (NULL module name) */
    printf("[1] Starting trace (output: %s)...\n", output_path);

    session = gum_trace_start(
        NULL,         /* module name: NULL = trace everything */
        0,            /* start address */
        0,            /* size */
        output_path   /* output file */
    );

    if (session == NULL)
    {
        fprintf(stderr, "ERROR: Failed to start trace session!\n");
        return 1;
    }

    printf("    Trace started.\n\n");

    /* Execute some traceable work */
    printf("[2] Running test workloads...\n");

    printf("    fibonacci(15) = %d\n", fibonacci(15));

    do_string_work();
    printf("    String work done.\n");

    do_math_work();
    printf("    Math work done.\n");

    /* Check intermediate stats */
    guint64 mid_count = gum_trace_get_record_count(session);
    printf("\n    Records so far: %llu\n", (unsigned long long)mid_count);

    /* Do more work */
    printf("    fibonacci(20) = %d\n", fibonacci(20));

    printf("\n[3] Stopping trace...\n");

    guint64 total = gum_trace_get_record_count(session);
    guint64 dropped = gum_trace_get_dropped_count(session);

    gum_trace_stop(session);

    printf("    Trace stopped.\n\n");

    /* Print results */
    printf("=== Results ===\n");
    printf("  Total records:   %llu\n", (unsigned long long)total);
    printf("  Dropped records: %llu\n", (unsigned long long)dropped);
    printf("  Output file:     %s\n", output_path);

    /* Check file size */
    FILE *f = fopen(output_path, "rb");
    if (f != NULL)
    {
        fseek(f, 0, SEEK_END);
        long size = ftell(f);
        fclose(f);
        printf("  File size:       %ld bytes (%.2f KB)\n", size, size / 1024.0);
    }

    printf("\n");
    printf("To analyze the trace:\n");
    printf("  ./trace_parser %s --stats\n", output_path);
    printf("  ./trace_parser %s --limit 20\n", output_path);
    printf("  ./trace_parser %s --filter-type call --limit 50\n", output_path);

    return 0;
}
